runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: 2.5.2

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
  secure: always